server:
  port: 8761

spring:
  application:
    name: eureka_server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  server:
    ####本地测试环境时 关闭自我保护机制,保证不可用服务及时踢出 默认为true
    enable-self-preservation: false
    ###清理间隔 单位毫秒,默认是90秒
    eviction-interval-timer-in-ms: 10000
    peer-node-connect-timeout-ms: 3000
    peer-node-read-timeout-ms: 3000
  instance:
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
    instance-id: 注册中心(${spring.cloud.client.ip-address}:${server.port})